### ISSUE TITLE
Build failure in nixos-unstable as pytest-runner is dropped

### ISSUE THREAD

**Issue by humaidq** [nix-community/authentik-nix#33]
Hello.

I have recently tested Authentik on the latest nixos-unstable, it fails to build after pytest-runner is dropped upstream: https://github.com/NixOS/nixpkgs/pull/328922

**Comment by WilliButz** [comment]
This issue is also covered by the comment here: https://github.com/nix-community/authentik-nix/issues/32#issuecomment-2367845474
