### ISSUE TITLE
Build getting stuck

### ISSUE THREAD

**Issue by erahhal** [nix-community/authentik-nix#36]
I'm trying to build with the latest NixOS stable, and the build gets stuck on the following:

```
[1/373/405 built, 4793 copied (10715.5 MiB), 3030.3 MiB DL] building goauthentik-website-docs-2024.8.4 (buildPhase): Running npm install --include=d
```

I've left it for hours and it doesn't move.

**Comment by erahhal** [comment]
I tested with 2024.8.3 as well and see the same thing, so something must have changed upstream rather than with the latest release.

**Comment by ImWuX** [comment]
Yup I second this. Cannot make changes to my server rn n o matter what

**Comment by firewalkwithm3** [comment]
I think it's due to a kernel bug and upgrading to the latest kernel has fixed the issue for me: https://github.com/NixOS/nixpkgs/issues/353709#issuecomment-2458957910

**Comment by erahhal** [comment]
@firewalkwithm3 Thanks for the info. Ugh, I need to stop using ZFS. It's locked to an older kernel.

**Comment by Ma27** [comment]
The patch will appear on 6.6 as well with the next round of backports, so even with ZFS that should be fine.

**Comment by ImWuX** [comment]
Yeah updating kernel solved it for me. Thanks!

**Comment by erahhal** [comment]
Forgot to close this. Yeah, it's resolved with a newer kernel.
